### ISSUE TITLE
use `process.kill` instead of exec-ing `kill`

### ISSUE THREAD

**Issue by jedwards1211** [dwyl/terminate#19]
is there some reason for this or were you guys not aware of the existence of `process.kill`?
cf #9

**Comment by nelsonic** [comment]
@jedwards1211 _good question_ we _could_ switch. 
https://nodejs.org/dist/latest-v6.x/docs/api/process.html#process_process_kill_pid_signal
do you have time to prep a PR? (_thanks_)

**Comment by jedwards1211** [comment]
yeah I was working on a PR but I'm having trouble getting 100% code coverage, I took care of all the uncovered lines istanbul was reporting but it still says I'm missing some branch without specifying what line it is.  Would you mind if I just upgrade istanbul as well and use it with nyc?  Hopefully that will help me figure it out.

**Comment by jedwards1211** [comment]
also, it is slightly awkward because `process.kill`ing one process in the tree _may_ kill child processes, and if the child pids come later in the array, those `process.kill` calls will throw an error since the children are gone.  So the semantics of `terminate` might have to change slightly.  I was thinking either:
- callback with `error` if `process.kill` threw an error for the top parent process (ignore errors on its descendants)
- poll until none of the processes are running anymore (using `process.kill(pid, 0)` to check for the existence of each process)

**Comment by nelsonic** [comment]
@jedwards1211 _at present we just ignore when a process does not exist_... feel free to try either approach and let us know how you get on.  and go for it with `nyc` 👍

**Comment by jedwards1211** [comment]
oh okay, that works.  I thought maybe linux `kill` would return nonzero in that case.

**Comment by jedwards1211** [comment]
@nelsonic actually when I preserved the present behavior with `process.kill` I was able to get the coverage to work without changing any deps.
