### ISSUE TITLE
processes don't seem to be killed immediately on windows

### ISSUE THREAD

**Issue by jedwards1211** [dwyl/terminate#26]
I increased the test timeouts once to fix my appveyor build but I'm still seeing it fail sometimes.

Maybe it would be best to make `terminate` wait until the processes have exited, for instance by polling every second?  We can use `process.kill(pid, 0)` to test if the child processes are running, even if the parent is not.

**Comment by nelsonic** [comment]
Yeah, worth a shot! 👍

**Comment by camj256** [comment]
did this ever get done. Same issue.

**Comment by nelsonic** [comment]
@camj256 _not yet_...!

**Comment by jedwards1211** [comment]
@nelsonic my PR #27 is ready btw

**Comment by nelsonic** [comment]
@jedwards1211 thanks for _reminding me_... 
I _saw_ you had updated your PR, and then got distracted by family over the holidays and lost it...
I _really_ need a better way to track which PRs are assigned to me for review...!

**Comment by jedwards1211** [comment]
@nelsonic not exactly what you're looking for, but you can use https://github.com/pulls/mentioned to see PRs where you've been mentioned

**Comment by jedwards1211** [comment]
@nelsonic on and there is https://github.com/pulls/assigned :)

**Comment by nelsonic** [comment]
@jedwards1211  https://github.com/pulls/assigned  works when I _remember_ to assign PR to myself... 😜

**Comment by nelsonic** [comment]
@camj256 please try `terminate@2.1.0` (_the latest version on NPM_) and let us know if you have more luck...! thanks! ✨

**Comment by nelsonic** [comment]
Suuuuuper old issue. `Windows` has had _many_ updates as has `Node.js` ... ⏳ 
guessing this is no longer a problem `else` there would be more comments in this thread. 💭 
Closing. ✅
