### ISSUE TITLE
Refactor the Code in terminate function to use (JavaScript The) "Good Parts" 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/terminate#29]
at present the code in this module _works_ as _expected_. 
but... it does not follow our "_style guide_": https://github.com/dwyl/goodparts
ideally, _all_ our projects should follow this guide to ensure we have _consistency_ across all our JS.

If anyone has the time/patience to re-factor the code in [`/terminate.js`](https://github.com/dwyl/terminate/blob/master/terminate.js) to conform to `goodparts` please comment on this issue to show your interest. 

### `Note2`: If you haven't already done so, please read and :star: the "Contributing Guide": https://github.com/dwyl/contributing to ensure that our "steps" are followed and someone can read your Pull Request without any delays. 👍 

The task(s) are:
+ [ ] clone the repo to your local machine
+ [ ] create a new branch called `goodparts-refactor`
+ [ ] `npm install goodparts --savedev` 
+ [ ] add the following line to the [`scripts` section of `package.json`](https://github.com/dwyl/terminate/blob/8179aa87868fc192b73334885215d5bb58f6765d/package.json#L6-L10) 
```
"lint": "node_modules/.bin/goodparts terminate.js"
```
+ [ ] run the linter `npm run lint`
+ [ ] update this issue with a screenshot of the error messages you see in your console/terminal, so that we know how many there were ...
+ [ ] now _attempt_ to run the "fix" with the following command: 
```
node_modules/.bin/goodparts terminate.js --fix
```
That should "_fix_" a _few_ of the "_basic_" code style issues, but it will not address any "_major_" ones.
+ [ ] _confirm_ the "_fix_" worked as expected by re-running the tests: `npm test`
+ [ ] Now the "_fun_" part: re-thinking the code to follow an alternative (_more beginner-friendly_) code style...! This will involve quite a few changes dependent on how many things the `goodparts` (ESLint) is reporting...
  + [ ] each time you make a change re-run the tests and lint. My _preferred_ way of doing this is to re-run my test & lint commands in two separate terminal windows/tabs using [`nodemon`](https://nodemon.io/) each time the file is updated.
+ [ ] Once all the warnings raised by `goodparts` have been resolved and the code conforms to the styleguide, commit your changes referencing this issue in your commit message.
+ [ ] finally, if that all worked, add the ["Repo Badge"](https://github.com/dwyl/goodparts/#repo-badge--) to the `README.md` [![JavaScript Style Guide: Good Parts](https://img.shields.io/badge/code%20style-goodparts-brightgreen.svg?style=flat)](https://github.com/dwyl/goodparts "JavaScript The Good Parts") to _signal_ to everyone that this repo conforms to our code style guide. 
+ [ ] once the badge is added to the readme make a commit to that effect: `git commit -m 'adds goodparts repo badge see: https://github.com/dwyl/repo-badges#goodparts-javascript-code-style-'`
+ [ ] push up your branch and create a pull request referencing this issue.

**Comment by mitchellporter** [comment]
Here is a screenshot of the errors I ran into when first running the linter:

<img width="770" alt="screen shot 2017-07-01 at 4 38 46 pm" src="https://user-images.githubusercontent.com/7875419/27766498-9c1abed0-5e86-11e7-9d16-f3b17d4fbd17.png">
