### ISSUE TITLE
Promise interface

### ISSUE THREAD

**Issue by callumlocke** [dwyl/terminate#32]
Thanks for writing this module.

A promise interface would make it more useful.

**Comment by nelsonic** [comment]
@callumlocke thanks for opening this issue. 
If you need a Promise interface simply use the Node.js ***`core`*** "promisify" function: `util.promisify` see: https://nodejs.org/api/util.html#util_util_promisify_original
Fore a detailed example see: http://2ality.com/2017/05/util-promisify.html

**Comment by nelsonic** [comment]
If a promise/async interface for this module is still required, very happy to accept a Pull Request adding the feature. 👍

**Comment by micalevisk** [comment]
@callumlocke what do you think on having this usage:

```js
const terminate = require('terminate/promise') // <<<


;(async () => {
  try {
    await terminate(process.pid)
    console.log("done") // NOTE: this won't be run as the process itself will be killed before.
  } catch (err) {
    console.log("Oopsy:", err) // handle errors in your preferred way.
  }
})()
```

?
