### ISSUE TITLE
Add a LICENSE file, please

### ISSUE THREAD

**Issue by coopr** [dwyl/terminate#33]
Thanks!

**Comment by nelsonic** [comment]
Hi @coopr! Thanks  for opening this issue. 
Happy to add a license _file_ if that's what you need.
At present we have `GPL v2` listed in the `package.json`:
https://github.com/dwyl/terminate/blob/9776c64d0ed171c91153561893c8eebc338503d0/package.json#L24
Do you need any _specific_ license?

**Comment by hrieke** [comment]
I'll chime in as well as a vote for the actual license file / text.
Also, GPL 2 _only_ or GPL 2 or later?
And just as long as you're in doing that, could you add proper headers to the code?
(Ya, I know, being *ick* picky...)

**Comment by coopr** [comment]
Ideally, you'd do this https://help.github.com/articles/adding-a-license-to-a-repository/

In my case, I'm asking for this because the automated process we use depends on a response from Github's API https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license regarding the license of each package we use - and, for this particular package, Github's API provides no response - because there is no detectable license in this repo.

**Comment by micalevisk** [comment]
looks like this can be closed now :smile: @nelsonic

https://github.com/dwyl/terminate/blob/master/LICENSE

**Comment by nelsonic** [comment]
Good point @micalevisk. 👍  (Thanks for the nudge... 😉)
