### ISSUE TITLE
Terminate hanging in docker container?

### ISSUE THREAD

**Issue by PorterK** [dwyl/terminate#34]
So I'm not sure if this is a docker issue or a terminate issue.

Here is my code block:

```js
  terminate(server.pid, (err) => {
    if (err) {
      console.log(err);
    }

    console.log(`[REBUILDING]: Change detected at ${path}`);

    server = spawn('npm', ['start']);

    server.stdout.on('data', function(data) {
        console.log(data.toString());
    });

    server.stderr.on('data', d => console.log(d.toString()))
  });
``` 

Basically, the first time I call this block it hangs (never gets to spawning the new process). The 2nd time, it actually builds (from the first time) but then errors out because the PID is being terminated twice.

Nothing special as far as the stack goes. Using child processes to run babel builds, chokidar to watch for changes & rebuild/restart the server as needed. This is running inside of a docker container which is where the weirdness might be.

I expect the server to restart after each time I save a file, it restarts every other file save. Chokidar is logging each time I save, so this must be an issue with terminate's compatibility with docker/docker compose.

**Comment by nelsonic** [comment]
@PorterK are you _able_ to test your code _outside_ of a Docker container to _isolate_ it?

**Comment by PorterK** [comment]
Yes, it works perfectly outside of the docker container, exactly as expected.

Here is the repo to test: https://github.com/pyazo/sump-thing-backend

`yarn watch` works but `docker-compose up` will result in the weird behavior.

**Comment by PorterK** [comment]
If you change the if statement to

```js
if (err) {
   console.error(err);
   return;
}
```

you'll see that the server never restarts (or even displays the `[RESTARTING]` console log) because it errors out.

**Comment by nelsonic** [comment]
@PorterK hmm... 
this is more to do with the Filesystem signals (`fs.watch`) in the Docker container that Node.js (Chokidar) is listening to. (_i.e. not really something we are going to be able to "debug"..._)

**Comment by PorterK** [comment]
Interesting. On the outside of the code block I did put a console log (for when changes happen in the file system) and it is fired consistently each time I reload.

From what I can gather, here is my best guess about what is happening:

- Reload happens, terminate is called
- PID _is_ killed but the callback isn't called (verifiable behavior... must be some timeout issue or something)
- 2nd reload happens, terminate is called again
- The PID is already dead, therefore never found, thus error.
- The callback _is_ called but with an error
- Because I don't return on error in this instance, the child process is started up again.
- Back to top on next reload.

As far as I can tell there aren't any issues with how Chokidar (or any other package in my stack) is behaving. Functions on either side of the terminate call behave consistently.

**Comment by PorterK** [comment]
@nelsonic Any updates on what this could be?

**Comment by nelsonic** [comment]
@PorterK sorry for delayed response, given that this is not an issue with `terminate` but rather with the **container** where it is being run, it's difficult for _us_ to debug it ... 😞  

"under the hood" `terminate` is just using node.js' `process.kill` method 
see: https://nodejs.org/api/process.html#process_process_kill_pid_signal

> "_Even though the name of this function is `process.kill()`, it is really just a **signal sender**, like the kill system call. The signal sent may do something other than kill the target process._"

i.e. it's up to `Docker` how to _handle_ the "kill" signal.
And it _appears_ that Docker is not _behaving_ as _expected_.

**Comment by PorterK** [comment]
@nelsonic hmmm ok, have you done any testing in docker with this before? I'll make an issue in the docker repo, but I'm wondering how we can test that docker is handling the kill function wrongly (so I can be more specific in the request)

Thanks for all the help!

**Comment by nelsonic** [comment]
Both `Docker` and `Node` have been updated _many_ times since this issue was opened. ⏳ 
I'm guessing that it resolved itself or there would be more comments in this thread. 💭 
Closing. ✅
