### ISSUE TITLE
The ps-tree package may be unsafe now. Better find an alternative.

### ISSUE THREAD

**Issue by haoqunjiang** [dwyl/terminate#35]
See:
https://github.com/indexzero/ps-tree/issues/33
https://github.com/dominictarr/event-stream/issues/116

**Comment by nelsonic** [comment]
@sodatea thanks for opening this issue. 👍 
we are _aware_ of the `ps-tree` / `event-stream` issue. 
Please keep in mind that `terminate` should _not_ be used in "_customer-facing_" code.
We use it _exclusively_ for "hot reloading" on or development machine.

**Comment by indexzero** [comment]
FYI `ps-tree@1.1.1` locked to `event-stream@3.3.4` (which if I read this thread correctly pre-dates the questionable changes). 

Thanks to folks for bringing it to my attention: https://github.com/indexzero/ps-tree/pull/34
