### ISSUE TITLE
Misleading JSDoc

### ISSUE THREAD

**Issue by morigs** [dwyl/terminate#46]
JSDoc in terminate.js says default signal is `SIGTERM`. But [actually](https://github.com/dwyl/terminate/blob/master/handlePsTreeCallback.js#L9), it is `SIGKILL`

**Comment by nelsonic** [comment]
Hi @morigs thanks for opening this issue. This looks like an out-of-date JSDoc. 🤦 
https://github.com/dwyl/terminate/blob/c6030569aa2d9e649f4975c316a5ad35734f961e/terminate.js#L11

If you have time, please update via Pull Request. Thanks very much.
