### ISSUE TITLE
Remove `console.log`s or expose option to squelch them

### ISSUE THREAD

**Issue by jarofghosts** [dwyl/terminate#5]
This module is great and works perfectly, but it would be nice to have a way to not output to stdout on kill. This has tripped me up while using it to make a command line tool that can be piped into other sources as it disrupts the output. I think that things are usually best to be silent unless something unexpected happens or they are asked to be verbose.

I would be happy to PR the change, but wanted to get your opinion on it as a possibility.

**Comment by nelsonic** [comment]
Agree 100% that console.logs should not be left in modules. :+1: 
We were using it for our purposes, but if you have a use for it too, please PR the removal.
We can always console.log in our callback if needed. 
Thanks!

**Comment by jarofghosts** [comment]
https://github.com/dwyl/terminate/pull/8

**Comment by micalevisk** [comment]
looks like this was solved :smiley: 

![image](https://user-images.githubusercontent.com/13461315/149425460-9c9efe26-94df-49a3-b4da-8517fb7409e2.png)
