### ISSUE TITLE
Doesn't actually call back when completed

### ISSUE THREAD

**Issue by jarofghosts** [dwyl/terminate#6]
The callback is called immediately after the `spawn`, which is asynchronous. It should instead be attached to the `'exit'` event of the spawn command so that you don't call it before the processes are _actually_ killed.

**Comment by nelsonic** [comment]
@jarofghosts I can see where this could be a problem.
If you have time to PR a change please do. :+1:

**Comment by jarofghosts** [comment]
https://github.com/dwyl/terminate/pull/7

**Comment by nelsonic** [comment]
fixed by #7 👍
