### ISSUE TITLE
Windows 7 killing not working

### ISSUE THREAD

**Issue by arrayoutofbounds** [dwyl/terminate#9]
I wrote code to terminate a node process on windows 7 but it says it cannot find 'ps' and then does not work. Is there a work around it?
regards

**Comment by leegee** [comment]
It would be helpful to advertise that this module is platform-specific.

See also https://github.com/indexzero/ps-tree/issues/13

**Comment by nelsonic** [comment]
@leegee you're right, we should _clearly_ state that Windows is not currently supported... sorry. :disappointed:

**Comment by jedwards1211** [comment]
Oh, I didn't realize you guys aren't using the latest version of `ps-tree` yet, haha
