### ISSUE TITLE
`npm upgrade` causes breakage. 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/terminate#91]
_Originally posted by @nikitaeverywhere in https://github.com/dwyl/terminate/issues/85#issuecomment-2199887016_

`npm upgrade` in my project made me drill down to this PR. You seem to have deployed a breaking change to NPM guys under a minor version:

1. New ts build error never seen before in my project

```sh
> pkg@1.2.0 build
> tsc && tsc-alias

.../test.ts:18:23 - error TS2307: Cannot find module 'terminate' or its corresponding type declarations.

18 import terminate from "terminate";
                         ~~~~~~~~~~~


Found 1 error in src/bin/du/test.ts:18
```

2. (more critical) invalid import in a dependent package

```
node:internal/modules/esm/resolve:303
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/zitro/Projects/pkg/node_modules/terminate/package.json imported from /Users/zitro/Projects/pkg/node_modules/pkg/dist/bin/du/test.js
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at packageResolve (node:internal/modules/esm/resolve:836:14)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.11.1
```

FYI @nelsonic @himself65 will be waiting for a fix

UPD I'm using `import terminate from "terminate";` and here's a sample tsconfig just in case:

<details>
  <summary>Spoiler</summary>

```json
{
  "compilerOptions": {
    "incremental": true,
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "allowJs": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "baseUrl": ".",
    "removeComments": false,
    "pretty": true,
    "strictNullChecks": true,
    "paths": {
      "@/const": ["./src/const/index.js"],
      "@/config": ["./src/config/index.js"],
      "@/types": ["./src/types/index.js"],
      "@/utils": ["./src/utils/index.js"],
      "@/*": ["./src/*"]
    }
  },
  "include": ["./src"],
  "exclude": ["node_modules"]
}
```
</details>

I'd advice to rollback this PR with a new minor version then fix.

**Comment by micalevisk** [comment]
https://github.com/dwyl/terminate/blob/87db76d66b8034d1fb3a8ba908d81ef1b348bcc4/package.json#L14

changing that to `"."` seems to fix that. I tested it locally

![image](https://github.com/dwyl/terminate/assets/13461315/8883e266-25a3-47f7-907b-2b9188ea25be)



https://nodejs.org/api/packages.html#exports-sugar

**Comment by nelsonic** [comment]
Cool. let's try that. 👌 (thanks @micalevisk)

**Comment by nelsonic** [comment]
Docs: https://nodejs.org/api/packages.html#package-entry-points

**Comment by nelsonic** [comment]
Given that others using this package will experience the "break" if they attempt to upgrade, 💔 
I've taken a few mins out of work-work to do the update. 🧑‍💻 ⌛ 

`terminate@2.8.0` published to NPM has the change recommended by @micalevisk 🤞 📦

**Comment by nelsonic** [comment]
@nikitaeverywhere I _agree_ that given that `2.7.0` does actually "break" imports it _should_ have been a **major** but we didn't _know_ that it would break imports when we published it. there's no way for us to test that _without_ publishing. 🙃 
_Hopefully_ `2.8.0` with @micalevisk suggested fix will indeed _fix_ imports and we don't _need_ a **major** release given that no new _features_ were introduced.
Buutttt ... if `2.8.0` does not fix the import then we can do a roll-back. 👌

**Comment by nikitaeverywhere** [comment]
@nelsonic I can confirm the issue is gone (at least in my build system ;) ). Upgraded to `2.8.0`. Thank you for a quick fix.

**Comment by nikitaeverywhere** [comment]
> there's no way for us to test that _without_ publishing. 🙃

You can try [npm link](https://docs.npmjs.com/cli/v10/commands/npm-link) next time to test it locally before publishing. Although, I'd advice to consider every similar imports/exports change as a breaking one and bump the major version of the package. I believe this is less relevant to backend-only packages overall; for instance front end ones use way more build systems which may result in more weird build-related bugs.

P.S. Thanks for the great package!
